import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import ts from 'typescript'

import {
	type ApiEngine,
	type ApiLanguage,
	apiEngines,
	apiFile,
	apiIndexFile,
	apiLanguageNames,
	apiLanguages,
} from './api'
import { checkout } from './repo'
import { alignTables } from './tables'

/**
 * The API pages: every public name of an engine in Go, Bun and Python,
 * generated from the source into docs/reference/<language>/<engine>.md, and
 * their index. `task reference` writes them and the tests fail when a page
 * is not what the source says, so a page is the code's doc comments and
 * nothing else.
 *
 * Go is read by web/reference/go and Python by web/reference/python.py, each
 * printing the Item shape below as JSON; TypeScript is read here, from the
 * declarations the compiler emits.
 */

export interface Item {
	name: string
	code: string
	/** markdown */
	doc: string
	members?: Item[]
}

/** Where each language keeps an engine. */
interface Sources {
	/** the Go package's directory, '' for the root's tinystore */
	go: string
	/** the engine's other Go packages, whose names the page writes with theirs */
	goAlso?: string[]
	/** sdk/js/src modules, in the order the page lists them */
	bun: string[]
	/** sdk/python/src/tinystore modules */
	python: string[]
}

const sources: Record<string, Sources> = {
	store: {
		go: '',
		bun: ['store', 'clock', 'errors', 'handles', 'cancel', 'time', 'wire/codec'],
		python: ['store', 'clock', 'errors', 'limits', '_page'],
	},
	sql: { go: 'sqldb', bun: ['sql'], python: ['sql'] },
	kv: {
		go: 'kv',
		bun: ['kv', 'limiter', 'quota', 'once', 'config'],
		python: ['kv', 'limiter', 'quota', 'config'],
	},
	jobs: { go: 'jobs', bun: ['jobs'], python: ['jobs'] },
	blobs: { go: 'blobs', bun: ['blobs'], python: ['blobs'] },
	records: {
		go: 'records',
		goAlso: ['records/console'],
		bun: ['records', 'logger', 'console', 'trace'],
		python: ['records', '_console'],
	},
	metrics: { go: 'metrics', bun: ['metrics'], python: ['metrics'] },
}

const fences: Record<ApiLanguage, string> = { bun: 'ts', python: 'python', go: 'go' }

export interface ApiPage {
	file: string
	markdown: string
}

/** Every engine's page in every language, then the index of them all. */
export function apiPages(root = checkout()): ApiPage[] {
	const bun = bunReader(root)
	const pages = apiEngines.flatMap(engine => {
		const source = sourcesOf(engine)
		return apiLanguages.map(language => {
			const items =
				language === 'go'
					? [
							...goItems(root, source.go),
							...(source.goAlso ?? []).flatMap(pkg => named(goItems(root, pkg), pkg)),
						]
					: language === 'python'
						? pythonItems(root, source.python)
						: bun(source.bun)
			return {
				file: apiFile(language, engine.slug),
				markdown: render(language, engine, source, items),
			}
		})
	})
	return [...pages, { file: apiIndexFile, markdown: indexPage() }]
}

function sourcesOf(engine: ApiEngine): Sources {
	const source = sources[engine.slug]
	if (source === undefined) {
		throw new Error(`reference.ts has no sources for the ${engine.slug} engine`)
	}
	return source
}

// --- rendering ---------------------------------------------------------------

function indexPage(): string {
	const header = ['Engine', ...apiLanguages.map(language => apiLanguageNames[language])]
	const rows = apiEngines.map(engine => [
		`[${engine.title}](../${engine.guide})`,
		...apiLanguages.map(language => `[${engine.title} API](${language}/${engine.slug}.md)`),
	])
	const table = [header, header.map(() => '---'), ...rows].map(row => `| ${row.join(' | ')} |`)

	return alignTables(
		[
			'# API reference',
			'',
			'Every public type, function and method of TinyStore in Bun and Node, Python and Go, ' +
				'generated from the source with its signature and doc comment. Use it to look up an ' +
				'exact name or type. The guides explain how to use each engine.',
			'',
			...table,
			'',
			'## For AI agents',
			'',
			"Each language's whole API is also one plain-text file at the root of the site: " +
				'`llms-bun.txt`, `llms-python.txt` and `llms-go.txt`. `llms.txt` lists them, and ' +
				'`llms-full.txt` contains the guides without the API pages.',
			'',
			'<!-- Generated by task reference. Edit web/src/lib/content/api.ts, not this file. -->',
			'',
		].join('\n'),
	)
}

function render(language: ApiLanguage, engine: ApiEngine, source: Sources, items: Item[]): string {
	const others = apiLanguages
		.filter(other => other !== language)
		.map(other => `[${apiLanguageNames[other]}](../${other}/${engine.slug}.md)`)
		.join(' and ')

	const lines = [
		`# ${engine.title} API for ${apiLanguageNames[language]}`,
		'',
		`Every public ${noun(language)} of ${what(engine)} in ${packageOf(language, source)}, ` +
			`generated from its source. The [${engine.title} guide](../../${engine.guide}) explains how ` +
			`to use them, and the ${others} pages list the same API.`,
		'',
	]
	for (const item of items) {
		lines.push(...section('##', item, fences[language]))
		for (const member of item.members ?? []) {
			lines.push(...section('###', member, fences[language]))
		}
	}
	lines.push(
		`<!-- Generated by task reference from ${sourceOf(language, source)}. Edit the doc comments there, not this file. -->`,
		'',
	)
	return lines.join('\n')
}

function section(level: string, item: Item, fence: string): string[] {
	const out = [`${level} ${item.name}`, '', `\`\`\`${fence}`, item.code.trimEnd(), '```', '']
	if (item.doc !== '') {
		out.push(escapeProse(item.doc), '')
	}
	return out
}

function what(engine: ApiEngine): string {
	return engine.slug === 'store' ? 'the store' : `the ${engine.title} engine`
}

function noun(language: ApiLanguage): string {
	return language === 'go' ? 'type, function and constant' : 'class, function and type'
}

function packageOf(language: ApiLanguage, source: Sources): string {
	if (language === 'go') {
		const paths = [source.go, ...(source.goAlso ?? [])].map(
			pkg => `\`github.com/tinyshed/tinystore${pkg === '' ? '' : `/${pkg}`}\``,
		)
		return paths.join(' and ')
	}
	return language === 'bun' ? '`@tinyshed/tinystore`' : '`tinystore`'
}

function sourceOf(language: ApiLanguage, source: Sources): string {
	if (language === 'go') {
		const dirs = [source.go, ...(source.goAlso ?? [])].map(pkg =>
			pkg === '' ? 'the root package' : `${pkg}/`,
		)
		return dirs.join(' and ')
	}
	if (language === 'bun') {
		return source.bun.map(module => `sdk/js/src/${module}.ts`).join(', ')
	}
	return source.python.map(module => `sdk/python/src/tinystore/${module}.py`).join(', ')
}

/**
 * A doc comment's `<` written as text, so that the site, which passes HTML
 * through, shows `Setting<string>` instead of opening a tag. Code spans and
 * indented code are left as they are.
 */
export function escapeProse(markdown: string): string {
	let code = false
	let blank = true
	return markdown
		.split('\n')
		.map(line => {
			if (/^```/.test(line)) {
				code = !code
			}
			const indented = /^( {4}|\t)/.test(line) && (blank || code)
			blank = line.trim() === '' || indented
			if (code || indented) {
				return line
			}
			return line
				.split(/(`[^`]*`)/)
				.map(part => (part.startsWith('`') ? part : part.replaceAll('<', '&lt;')))
				.join('')
		})
		.join('\n')
}

// --- Go and Python, by their own programs ------------------------------------

/** A sub-package's items, each named as a program writes it: console.Handler. */
function named(items: Item[], pkg: string): Item[] {
	const prefix = `${pkg.slice(pkg.lastIndexOf('/') + 1)}.`
	return items.map(item => ({
		...item,
		name: prefix + item.name,
		members: item.members?.map(member => ({ ...member, name: prefix + member.name })),
	}))
}

function goItems(root: string, pkg: string): Item[] {
	const importPath = `github.com/tinyshed/tinystore${pkg === '' ? '' : `/${pkg}`}`
	const out = execFileSync('go', ['run', './reference/go', join(root, pkg), importPath], {
		cwd: join(root, 'web'),
		env: { ...process.env, GOWORK: 'off' },
		encoding: 'utf8',
	})
	return (JSON.parse(out) as { items: Item[] }).items
}

function pythonItems(root: string, modules: string[]): Item[] {
	const script = join(root, 'web/reference/python.py')
	const out = execFileSync(python(), [script, join(root, 'sdk/python/src/tinystore'), ...modules], {
		encoding: 'utf8',
		env: { ...process.env, PYTHONIOENCODING: 'utf-8', PYTHONUTF8: '1' },
	})
	return (JSON.parse(out) as { items: Item[] }).items
}

// Windows's python3 is a shortcut to the Store unless Python came from there
function python(): string {
	return process.env.PYTHON ?? (process.platform === 'win32' ? 'python' : 'python3')
}

// --- TypeScript, from the declarations the compiler emits --------------------

/**
 * A reader of sdk/js's modules. A name is public when index.ts exports it
 * or Store keeps an instance of it, as store.kv keeps a Kv.
 */
function bunReader(root: string): (modules: string[]) => Item[] {
	const source = join(root, 'sdk/js/src')
	const declarations = emitDeclarations(source)
	const exported = exportedNames(readFileSync(join(source, 'index.ts'), 'utf8'))
	const kept = keptByStore(readFileSync(join(source, 'store.ts'), 'utf8'))

	return modules => {
		const items: Item[] = []
		for (const module of modules) {
			const text = declarations.get(module)
			if (text === undefined) {
				throw new Error(`the compiler emitted no declarations for sdk/js/src/${module}.ts`)
			}
			const isPublic = (name: string) =>
				exported.has(`./${module}.ts:${name}`) || exported.has(`./${module}.ts:*`) || kept.has(name)
			items.push(...declarationItems(text, isPublic))
		}
		return items
	}
}

/** Each module's declarations by its path under src, without .ts: `kv`, `wire/codec`. */
function emitDeclarations(source: string): Map<string, string> {
	const program = ts.createProgram([join(source, 'index.ts')], {
		target: ts.ScriptTarget.ESNext,
		module: ts.ModuleKind.Preserve,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		allowImportingTsExtensions: true,
		rewriteRelativeImportExtensions: true,
		resolveJsonModule: true,
		strict: true,
		exactOptionalPropertyTypes: true,
		skipLibCheck: true,
		declaration: true,
		emitDeclarationOnly: true,
		types: [],
	})
	const out = new Map<string, string>()
	program.emit(undefined, (file, text) => {
		out.set(
			relative(source, file)
				.replace(/\\/g, '/')
				.replace(/\.d\.ts$/, ''),
			text,
		)
	})
	return out
}

/**
 * What index.ts exports, as `./kv.ts:Bucket`: the module and the name it has
 * there, since metrics' Bucket is exported as MetricsBucket beside kv's.
 * `export *` is `./errors.ts:*`.
 */
function exportedNames(index: string): Set<string> {
	const file = ts.createSourceFile('index.ts', index, ts.ScriptTarget.ESNext)
	const names = new Set<string>()
	for (const statement of file.statements) {
		if (!ts.isExportDeclaration(statement) || statement.moduleSpecifier === undefined) {
			continue
		}
		const from = (statement.moduleSpecifier as ts.StringLiteral).text
		const clause = statement.exportClause
		if (clause === undefined) {
			names.add(`${from}:*`)
		} else if (ts.isNamedExports(clause)) {
			for (const element of clause.elements) {
				names.add(`${from}:${(element.propertyName ?? element.name).text}`)
			}
		}
	}
	return names
}

/** The classes of Store's own readonly fields: `readonly kv: Kv`. */
function keptByStore(store: string): Set<string> {
	const file = ts.createSourceFile('store.ts', store, ts.ScriptTarget.ESNext)
	const kept = new Set<string>()
	const visit = (node: ts.Node) => {
		if (ts.isClassDeclaration(node) && node.name?.text === 'Store') {
			for (const member of node.members) {
				if (ts.isPropertyDeclaration(member) && member.type !== undefined) {
					kept.add(member.type.getText(file))
				}
			}
		}
		ts.forEachChild(node, visit)
	}
	visit(file)
	return kept
}

function declarationItems(text: string, isPublic: (name: string) => boolean): Item[] {
	const file = ts.createSourceFile('module.d.ts', text, ts.ScriptTarget.ESNext, true)
	const items: Item[] = []
	for (const statement of file.statements) {
		const name = declaredName(statement)
		if (name === undefined || !isPublic(name)) {
			continue
		}
		const last = items.at(-1)
		if (ts.isFunctionDeclaration(statement) && last?.name === name) {
			last.code += `\n${codeOf(statement, file)}`
			last.doc ||= docOf(statement, file)
			continue
		}
		items.push(
			ts.isClassDeclaration(statement)
				? classItem(statement, file)
				: { name, code: codeOf(statement, file), doc: docOf(statement, file) },
		)
	}
	return items
}

function declaredName(statement: ts.Statement): string | undefined {
	if (
		ts.isClassDeclaration(statement) ||
		ts.isInterfaceDeclaration(statement) ||
		ts.isTypeAliasDeclaration(statement) ||
		ts.isFunctionDeclaration(statement) ||
		ts.isEnumDeclaration(statement)
	) {
		return statement.name?.text
	}
	return undefined
}

function classItem(node: ts.ClassDeclaration, file: ts.SourceFile): Item {
	const name = node.name?.text ?? ''
	const fields: string[] = []
	const members: Item[] = []
	for (const member of node.members) {
		if (!isPublicMember(member)) {
			continue
		}
		if (ts.isPropertyDeclaration(member)) {
			fields.push(`    ${codeOf(member, file)}`)
			continue
		}
		if (!ts.isMethodDeclaration(member) && !ts.isGetAccessor(member)) {
			continue
		}
		const memberName = `${name}.${member.name.getText(file)}`
		const last = members.at(-1)
		if (last?.name === memberName) {
			last.code += `\n${codeOf(member, file)}`
			last.doc ||= docOf(member, file)
			continue
		}
		members.push({ name: memberName, code: codeOf(member, file), doc: docOf(member, file) })
	}

	const head = text(file, node.getStart(file), node.members.pos).replace(/^export (declare )?/, '')
	const code = fields.length === 0 ? `${head}}` : `${head}\n${fields.join('\n')}\n}`
	return { name, code: code.replace(/\{\s*\n?\}$/, '{}'), doc: docOf(node, file), members }
}

// a constructor takes the connection, so a program never calls one
function isPublicMember(member: ts.ClassElement): boolean {
	if (ts.isConstructorDeclaration(member) || ts.isPrivateIdentifier(member.name ?? member)) {
		return false
	}
	const modifiers = ts.canHaveModifiers(member) ? (ts.getModifiers(member) ?? []) : []
	return !modifiers.some(
		m => m.kind === ts.SyntaxKind.PrivateKeyword || m.kind === ts.SyntaxKind.ProtectedKeyword,
	)
}

/** The declaration as written, its doc comment and `export declare` left out. */
function codeOf(node: ts.Node, file: ts.SourceFile): string {
	return text(file, node.getStart(file), node.end)
		.replace(/^export (declare )?/, '')
		.replace(/;$/gm, '')
}

function text(file: ts.SourceFile, start: number, end: number): string {
	return file.text.slice(start, end).trim()
}

/** A JSDoc comment's text as markdown, its stars and `@` tags' braces gone. */
function docOf(node: ts.Node, file: ts.SourceFile): string {
	const ranges = ts.getLeadingCommentRanges(file.text, node.getFullStart()) ?? []
	const jsdoc = ranges.filter(r => file.text.startsWith('/**', r.pos)).at(-1)
	if (jsdoc === undefined) {
		return ''
	}
	const body = file.text.slice(jsdoc.pos + 3, jsdoc.end - 2)
	const lines = body.split('\n').map(line => line.replace(/^\s*\* ?/, ''))
	return lines
		.join('\n')
		.replace(/\{@link\s+([^}|\s]+)(?:[\s|]+([^}]+))?\}/g, (_, target, label) =>
			label === undefined ? `\`${target}\`` : label,
		)
		.trim()
}

// --- the task -----------------------------------------------------------------

/** Writes every API page from the source, returning the files that changed. */
export function writeApiPages(root = checkout()): string[] {
	const changed: string[] = []
	for (const page of apiPages(root)) {
		const path = join(root, page.file)
		let before = ''
		try {
			before = readFileSync(path, 'utf8')
		} catch {
			// a new page
		}
		if (before !== page.markdown) {
			mkdirSync(dirname(path), { recursive: true })
			writeFileSync(path, page.markdown)
			changed.push(page.file)
		}
	}
	return changed
}

if (import.meta.main) {
	for (const file of writeApiPages()) {
		process.stdout.write(`${file}: written from the source\n`)
	}
}
